trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

schedules:
- cron: '0 2 * * 1,3,5'
  displayName: 'Scheduled run at 10 AM GMT+8 every Monday, Wednesday, and Friday'
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm install -g playwright
  displayName: 'Install dependencies and Playwright'

- script: |
    npx playwright install-deps
  displayName: 'Install Playwright dependencies'

- script: |
    chmod +x run-changed-tests.sh
    ./run-changed-tests.sh
  displayName: 'Run tests based on scenario'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish test results'
  condition: succeededOrFailed()
